sonar.projectKey=HeptaCode-UniPD_CodeGuardian
sonar.projectName=Code Guardian
sonar.projectVersion=1.0

sonar.organization=heptacode-unipd

sonar.sources=./frontend/src
sonar.language=ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info